/**
 * @license
 * Lo-Dash 1.3.1 (Custom Build) lodash.com/license
 * Build: `lodash exports="global" include="each" --minify --output src/js/lodash.js`
 * Underscore.js 1.4.4 underscorejs.org/LICENSE
 */
;!function(r){function t(r){return typeof r.toString!="function"&&typeof(r+"")=="string"}function n(r){r.length=0,g.length<b&&g.push(r)}function e(r){var t=r.k;t&&e(t),r.b=r.k=r.object=r.number=r.string=null,h.length<b&&h.push(r)}function o(){}function u(){var r=h.pop()||{a:"",b:null,c:"",k:null,"false":!1,d:"",e:"",f:"","null":!1,number:null,object:null,push:null,g:null,string:null,h:"","true":!1,undefined:!1,i:!1,j:!1};r.g=v,r.b=r.c=r.f=r.h="",r.e="r",r.i=!0,r.j=!!K;for(var t,n=0;t=arguments[n];n++)for(var u in t)r[u]=t[u];
n=r.a,r.d=/^[^,]+/.exec(n)[0],t=Function,n="return function("+n+"){",u="var m,r="+r.d+",C="+r.e+";if(!r)return C;"+r.h+";",r.b?(u+="var s=r.length;m=-1;if("+r.b+"){",L.unindexedChars&&(u+="if(q(r)){r=r.split('')}"),u+="while(++m<s){"+r.f+";}}else{"):L.nonEnumArgs&&(u+="var s=r.length;m=-1;if(s&&n(r)){while(++m<s){m+='';"+r.f+";}}else{"),L.enumPrototypes&&(u+="var E=typeof r=='function';"),L.enumErrorProps&&(u+="var D=r===j||r instanceof Error;");var a=[];if(L.enumPrototypes&&a.push('!(E&&m=="prototype")'),L.enumErrorProps&&a.push('!(D&&(m=="message"||m=="name"))'),r.i&&r.j)u+="var A=-1,B=z[typeof r]&&t(r),s=B?B.length:0;while(++A<s){m=B[A];",a.length&&(u+="if("+a.join("&&")+"){"),u+=r.f+";",a.length&&(u+="}"),u+="}";
else if(u+="for(m in r){",r.i&&a.push("l.call(r, m)"),a.length&&(u+="if("+a.join("&&")+"){"),u+=r.f+";",a.length&&(u+="}"),u+="}",L.nonEnumShadows){for(u+="if(r!==y){var h=r.constructor,p=r===(h&&h.prototype),e=r===H?G:r===j?i:J.call(r),v=w[e];",k=0;7>k;k++)u+="m='"+r.g[k]+"';if((!(p&&v[m])&&l.call(r,m))",r.i||(u+="||(!v[m]&&r[m]!==y[m])"),u+="){"+r.f+"}";u+="}"}return(r.b||L.nonEnumArgs)&&(u+="}"),u+=r.c+";return C",t=t("i,j,l,n,o,q,t,u,y,z,w,G,H,J",n+u+"}"),e(r),t(w,I,D,c,T,l,K,o,B,x,J,A,F,q)}function c(r){return q.call(r)==d
}function a(r,e,u,f,l,s){var p=u===m;if(typeof u=="function"&&!p){u=o.createCallback(u,f,2);var h=u(r,e);if(typeof h!="undefined")return!!h}if(r===e)return 0!==r||1/r==1/e;var b=typeof r,y=typeof e;if(r===r&&(!r||"function"!=b&&"object"!=b)&&(!e||"function"!=y&&"object"!=y))return!1;if(null==r||null==e)return r===e;if(y=q.call(r),b=q.call(e),y==d&&(y=C),b==d&&(b=C),y!=b)return!1;switch(y){case O:case E:return+r==+e;case _:return r!=+r?e!=+e:0==r?1/r==1/e:r==+e;case S:case A:return r==e+""}if(b=y==j,!b){if(D.call(r,"__wrapped__")||D.call(e,"__wrapped__"))return a(r.__wrapped__||r,e.__wrapped__||e,u,f,l,s);
if(y!=C||!L.nodeClass&&(t(r)||t(e)))return!1;var y=!L.argsObject&&c(r)?Object:r.constructor,v=!L.argsObject&&c(e)?Object:e.constructor;if(y!=v&&(!i(y)||!(y instanceof y&&i(v)&&v instanceof v)))return!1}for(v=!l,l||(l=g.pop()||[]),s||(s=g.pop()||[]),y=l.length;y--;)if(l[y]==r)return s[y]==e;var w=0,h=!0;if(l.push(r),s.push(e),b){if(y=r.length,w=e.length,h=w==r.length,!h&&!p)return h;for(;w--;)if(b=y,v=e[w],p)for(;b--&&!(h=a(r[b],v,u,f,l,s)););else if(!(h=a(r[w],v,u,f,l,s)))break;return h}return U(e,function(t,n,e){return D.call(e,n)?(w++,h=D.call(r,n)&&a(r[n],t,u,f,l,s)):void 0
}),h&&!p&&U(r,function(r,t,n){return D.call(n,t)?h=-1<--w:void 0}),v&&(n(l),n(s)),h}function i(r){return typeof r=="function"}function f(r){return!(!r||!x[typeof r])}function l(r){return typeof r=="string"||q.call(r)==A}function s(r,t,n){if(t&&typeof n=="undefined"&&T(r)){n=-1;for(var e=r.length;++n<e&&false!==t(r[n],n,r););}else Q(r,t,n);return r}function p(r){return r}var g=[],h=[],m={},b=40,y=(y=/\bthis\b/)&&y.test(function(){return this})&&y,v="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),d="[object Arguments]",j="[object Array]",O="[object Boolean]",E="[object Date]",w="[object Error]",_="[object Number]",C="[object Object]",S="[object RegExp]",A="[object String]",x={"boolean":!1,"function":!0,object:!0,number:!1,string:!1,undefined:!1},P=x[typeof global]&&global;
!P||P.global!==P&&P.window!==P||(r=P);var I=Error.prototype,B=Object.prototype,F=String.prototype,P=RegExp("^"+(B.valueOf+"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/valueOf|for [^\]]+/g,".+?")+"$"),z=Function.prototype.toString,D=B.hasOwnProperty,N=B.propertyIsEnumerable,q=B.toString,R=P.test(R=q.bind)&&R,$=P.test($=Object.create)&&$,M=P.test(M=Array.isArray)&&M,G=P.test(G=Object.keys)&&G,$=P.test(r.attachEvent),H=R&&!/\n|true/.test(R+$),J={};J[j]=J[E]=J[_]={constructor:!0,toLocaleString:!0,toString:!0,valueOf:!0},J[O]=J[A]={constructor:!0,toString:!0,valueOf:!0},J[w]=J["[object Function]"]=J[S]={constructor:!0,toString:!0},J[C]={constructor:!0},function(){for(var r=v.length;r--;){var t,n=v[r];
for(t in J)D.call(J,t)&&!D.call(J[t],n)&&(J[t][n]=!1)}}();var L=o.support={};!function(){var r=function(){this.x=1},t=[];r.prototype={valueOf:1,y:1};for(var n in new r)t.push(n);for(n in arguments);L.argsObject=arguments.constructor==Object&&!(arguments instanceof Array),L.argsClass=c(arguments),L.enumErrorProps=N.call(I,"message")||N.call(I,"name"),L.enumPrototypes=N.call(r,"prototype"),L.fastBind=R&&!H,L.nonEnumArgs=0!=n,L.nonEnumShadows=!/valueOf/.test(t),L.unindexedChars="xx"!="x"[0]+Object("x")[0];
try{L.nodeClass=!(q.call(document)==C&&!({toString:0}+""))}catch(e){L.nodeClass=!0}}(1),$={a:"f,d,I",h:"d=d&&typeof I=='undefined'?d:u.createCallback(d,I)",b:"typeof s=='number'",f:"if(d(r[m],m,f)===false)return C"},P={h:"if(!z[typeof r])return C;"+$.h,b:!1},L.argsClass||(c=function(r){return r?D.call(r,"callee"):!1});var T=M||function(r){return r?typeof r=="object"&&q.call(r)==j:!1},V=u({a:"x",e:"[]",h:"if(!(z[typeof x]))return C",f:"C.push(m)"}),K=G?function(r){return f(r)?L.enumPrototypes&&typeof r=="function"||L.nonEnumArgs&&r.length&&c(r)?V(r):G(r):[]
}:V,Q=u($),U=u($,P,{i:!1});i(/x/)&&(i=function(r){return typeof r=="function"&&"[object Function]"==q.call(r)}),o.createCallback=function(r,t,n){if(null==r)return p;var e=typeof r;if("function"!=e){if("object"!=e)return function(t){return t[r]};var o=K(r);return function(t){for(var n=o.length,e=!1;n--&&(e=a(t[o[n]],r[o[n]],m)););return e}}return typeof t=="undefined"||y&&!y.test(z.call(r))?r:1===n?function(n){return r.call(t,n)}:2===n?function(n,e){return r.call(t,n,e)}:4===n?function(n,e,o,u){return r.call(t,n,e,o,u)
}:function(n,e,o){return r.call(t,n,e,o)}},o.forEach=s,o.forIn=U,o.keys=K,o.each=s,o.identity=p,o.isArguments=c,o.isArray=T,o.isEqual=a,o.isFunction=i,o.isObject=f,o.isString=l,o.VERSION="1.3.1",r._=o}(this);